name: twirpd_protoc_plugin
version: 0.0.2
description: Protoc compiler plugin to generate Dart code and Twirp clients.
homepage: https://github.com/cheddar-me/twirpd-protoc-plugin

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  protoc_plugin: ^20.0.1
  dart_style: ^2.2.4
  fixnum: '>=0.10.9 <2.0.0'

executables:
  protoc-gen-twirpd: twirpd_protoc_plugin
  
